[project]
name = "xero-accounting-reports"
dynamic = ["version"]
readme = "README.md"
requires-python = "~=3.13.0"
dependencies = [
    "datadirtest[vcr] @ git+https://github.com/keboola/datadirtest.git@feature/vcr-testing",
    "keboola-component>=1.6.10",
    "keboola-http-client>=1.0.1",
    "keboola-utils>=1.1.0",
    "pydantic>=2.11.3",
    "pytest",
    "responses>=0.25.0",
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "ruff>=0.13.3",
]

[tool.ruff]
line-length = 120
